### ISSUE TITLE
Release `v0.6.2`

### ISSUE THREAD

**Issue by jank324** [desy-ml/cheetah#94]
## ToDos for release 0.6.2

 - [x] Add charge to the `ParameterBeam` and `ParticleBeam` classes (see #86)
 - [x] Add opt-in speed optimisations (see #88)
 - [x] Fix the transfer maps in `Drift` and `Dipole`; Add R56 in horizontal and vertical correctors modelling (see #90)
 - [ ] ~~Refactor `beam.empty` (see #93)~~
 - [x] Fix CPU/GPU mismatch (see #97)
 - [x] NX Tables import (#96)

**Comment by jank324** [comment]
I agree, but I think this is something to consider after v1.0.0 (right now the leading "v0." is just meant to indicate a pre-release version like it does in Gymnasium). But the important question this raises is: When do we move to v1.0.0?

**Comment by jank324** [comment]
So there is one task left here ... nice! I think #100 is something for a `v0.6.3` or `v0.7.0` depending on how severely it introduces breaking changes if and when we do it. And then we can think about `v1.0.0`.

**Comment by jank324** [comment]
I think `v0.6.2` should become the paper reference release.

We can probably also skip the empty beam feature for this release.

**Comment by jank324** [comment]
Wait for #117 to be merged

**Comment by jank324** [comment]
I think we should move this release ASAP.

**Comment by jank324** [comment]
- [] Run tests on GPU before release

**Comment by jank324** [comment]
... and published! 🚀
